# obsolete alternative to renovate bot (custom script for same purpose)
name: Version Update Check

# run on push if there are changes in the paths listed below
on:
  schedule:
    - cron: '0 0 * * 0' # sunday at midnight
  workflow_dispatch: # allow workflow to be triggered manually

jobs:
  # workflow
  version_update:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
      
      - name: Dependency Update
        run: docker run --rm renovate/renovate --conan
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONAN_USER: ${{ secrets.CONAN_USER }}
          CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
        
