# obsolete alternative to renovate bot (custom script for same purpose)
name: Version Update Check

# run on push if there are changes in the paths listed below
on:
  schedule:
    - cron: '0 0 * * 0' # sunday at midnight
  workflow_dispatch: # allow workflow to be triggered manually

jobs:
  # workflow
  version_update:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
      
      - name: Prepare Python
        run: pip install -r scripts/requirements.txt
        shell: cmd

      - name: Update dependencies
        env:
          GH_REPO: ${{ github.repository }}
        run:  python scripts/update_dependencies.py
      