name: Version Update Check

# run regularly or on demand
on:
  schedule:
    - cron: '0 0 * * *' # at midnight
  workflow_dispatch: # allow workflow to be triggered manually

jobs:
  # workflow
  version_update:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
      
      - name: Ensure required python packages
        run: pip install -r scripts/requirements.txt
        shell: cmd

      - name: Update dependencies
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
        run:  python scripts/update_dependencies.py
      
